const cityCountryMapping = {
  "Africa/Abidjan": "Abiyán, Costa de Marfil",
  "Africa/Accra": "Accra, Ghana",
  "Africa/Addis_Ababa": "Addis Abeba, Etiopía",
  "Africa/Algiers": "Argel, Argelia",
  "Africa/Asmera": "Asmara, Eritrea",
  "Africa/Bamako": "Bamako, Malí",
  "Africa/Bangui": "Bangui, República Centroafricana",
  "Africa/Banjul": "Banjul, Gambia",
  "Africa/Bissau": "Bissau, Guinea-Bisáu",
  "Africa/Blantyre": "Blantyre, Malaui",
  "Africa/Brazzaville": "Brazzaville, Congo",
  "Africa/Bujumbura": "Bujumbura, Burundi",
  "Africa/Cairo": "El Cairo, Egipto",
  "Africa/Casablanca": "Casablanca, Marruecos",
  "Africa/Ceuta": "Ceuta, España",
  "Africa/Conakry": "Conakry, Guinea",
  "Africa/Dakar": "Dakar, Senegal",
  "Africa/Dar_es_Salaam": "Dar es Salaam, Tanzania",
  "Africa/Djibouti": "Yibuti, Yibuti",
  "Africa/Douala": "Douala, Camerún",
  "Africa/El_Aaiun": "El Aaiún, Sáhara Occidental",
  "Africa/Freetown": "Freetown, Sierra Leona",
  "Africa/Gaborone": "Gaborone, Botsuana",
  "Africa/Harare": "Harare, Zimbabue",
  "Africa/Johannesburg": "Johannesburgo, Sudáfrica",
  "Africa/Kampala": "Kampala, Uganda",
  "Africa/Kinshasa": "Kinshasa, Congo",
  "Africa/Kisumu": "Kisumu, Kenia",
  "Africa/Lagos": "Lagos, Nigeria",
  "Africa/Libreville": "Libreville, Gabón",
  "Africa/Lome": "Lomé, Togo",
  "Africa/Luanda": "Luanda, Angola",
  "Africa/Lubumbashi": "Lubumbashi, Congo",
  "Africa/Lusaka": "Lusaka, Zambia",
  "Africa/Malabo": "Malabo, Guinea Ecuatorial",
  "Africa/Maputo": "Maputo, Mozambique",
  "Africa/Maseru": "Maseru, Lesoto",
  "Africa/Mbabane": "Mbabane, Esuatini",
  "Africa/Mogadishu": "Mogadiscio, Somalia",
  "Africa/Monrovia": "Monrovia, Liberia",
  "Africa/Nairobi": "Nairobi, Kenia",
  "Africa/Ndjamena": "N'Djamena, Chad",
  "Africa/Niamey": "Niamey, Níger",
  "Africa/Nouakchott": "Nouakchott, Mauritania",
  "Africa/Ouagadougou": "Ouagadougou, Burkina Faso",
  "Africa/Porto-Novo": "Porto-Novo, Benín",
  "Africa/Sao_Tome": "São Tomé, Santo Tomé y Príncipe",
  "Africa/Timbuktu": "Tombuctú, Malí",
  "Africa/Tunis": "Túnez, Túnez",
  "Africa/Windhoek": "Windhoek, Namibia",
  "America/Adak": "Adak, EE.UU. (Hawái-Aleutianas)",
  "America/Anchorage": "Anchorage, EE.UU. (Alaska)",
  "America/Anguilla": "Anguila, Anguila",
  "America/Antigua": "Antigua, Antigua y Barbuda",
  "America/Araguaina": "Araguaina, Brasil",
  "America/Argentina/Buenos_Aires": "Buenos Aires, Argentina",
  "America/Argentina/Catamarca": "Catamarca, Argentina",
  "America/Argentina/ComodRivadavia": "Comodoro Rivadavia, Argentina",
  "America/Argentina/Jujuy": "Jujuy, Argentina",
  "America/Argentina/La_Rioja": "La Rioja, Argentina",
  "America/Argentina/Mendoza": "Mendoza, Argentina",
  "America/Argentina/Rio_Gallegos": "Río Gallegos, Argentina",
  "America/Argentina/Salta": "Salta, Argentina",
  "America/Argentina/San_Juan": "San Juan, Argentina",
  "America/Argentina/San_Luis": "San Luis, Argentina",
  "America/Argentina/Tucuman": "Tucumán, Argentina",
  "America/Argentina/Ushuaia": "Ushuaia, Argentina",
  "America/Asuncion": "Asunción, Paraguay",
  "America/Atikokan": "Atikokan, Canadá",
  "America/Bahia": "Bahía, Brasil",
  "America/Barbados": "Barbados, Barbados",
  "America/Belem": "Belém, Brasil",
  "America/Belize": "Belice, Belice",
  "America/Boa_Vista": "Boa Vista, Brasil",
  "America/Bogota": "Bogotá, Colombia",
  "America/Boise": "Boise, EE.UU. (Montaña)",
  "America/Cambridge_Bay": "Cambridge Bay, Canadá",
  "America/Campo_Grande": "Campo Grande, Brasil",
  "America/Cancun": "Cancún, México",
  "America/Caracas": "Caracas, Venezuela",
  "America/Cayenne": "Cayenne, Guayana Francesa",
  "America/Cayman": "Islas Caimán, Islas Caimán",
  "America/Chicago": "Chicago, EE.UU. (Central)",
  "America/Chihuahua": "Chihuahua, México",
  "America/Colima": "Colima, México",
  "America/Costa_Rica": "San José, Costa Rica",
  "America/Creston": "Creston, Canadá",
  "America/Cuiaba": "Cuiabá, Brasil",
  "America/Curacao": "Curazao, Curazao",
  "America/Danmarkshavn": "Danmarkshavn, Groenlandia",
  "America/Dawson": "Dawson, Canadá",
  "America/Dawson_Creek": "Dawson Creek, Canadá",
  "America/Denver": "Denver, EE.UU. (Montaña)",
  "America/Detroit": "Detroit, EE.UU. (Este)",
  "America/Dominica": "Dominica, Dominica",
  "America/Edmonton": "Edmonton, Canadá",
  "America/Eirunepe": "Eirunepé, Brasil",
  "America/El_Salvador": "San Salvador, El Salvador",
  "America/Fortaleza": "Fortaleza, Brasil",
  "America/Fort_Nelson": "Fort Nelson, Canadá",
  "America/Godthab": "Nuuk, Groenlandia",
  "America/Goose_Bay": "Goose Bay, Canadá",
  "America/Grand_Turk": "Grand Turk, Islas Turcas y Caicos",
  "America/Grenada": "Granada, Granada",
  "America/Guadeloupe": "Guadalupe, Guadalupe",
  "America/Guatemala": "Guatemala, Guatemala",
  "America/Guyana": "Georgetown, Guyana",
  "America/Halifax": "Halifax, Canadá",
  "America/Havana": "La Habana, Cuba",
  "America/Hermosillo": "Hermosillo, México",
  "America/Indiana/Indianapolis": "Indianápolis, EE.UU. (Este)",
  "America/Indiana/Knox": "Knox, EE.UU. (Central)",
  "America/Indiana/Marengo": "Marengo, EE.UU. (Este)",
  "America/Indiana/Petersburg": "Petersburg, EE.UU. (Este)",
  "America/Indiana/Tell_City": "Tell City, EE.UU. (Central)",
  "America/Indiana/Vevay": "Vevay, EE.UU. (Este)",
  "America/Indiana/Vincennes": "Vincennes, EE.UU. (Este)",
  "America/Indiana/Winamac": "Winamac, EE.UU. (Central)",
  "America/Inuvik": "Inuvik, Canadá",
  "America/Iqaluit": "Iqaluit, Canadá",
  "America/Jamaica": "Kingston, Jamaica",
  "America/Jujuy": "Jujuy, Argentina",
  "America/Juneau": "Juneau, EE.UU. (Alaska)",
  "America/Kentucky/Louisville": "Louisville, EE.UU. (Este)",
  "America/Kentucky/Monticello": "Monticello, EE.UU. (Este)",
  "America/Kralendijk": "Kralendijk, Bonaire",
  "America/La_Paz": "La Paz, Bolivia",
  "America/Lima": "Lima, Perú",
  "America/Los_Angeles": "Los Ángeles, EE.UU. (Pacífico)",
  "America/Louisville": "Louisville, EE.UU. (Este)",
  "America/Maceio": "Maceió, Brasil",
  "America/Managua": "Managua, Nicaragua",
  "America/Martinique": "Fort-de-France, Martinica",
  "America/Matamoros": "Matamoros, México",
  "America/Mexico_City": "Ciudad de México, México",
  "America/Miquelon": "San Pedro y Miquelón, San Pedro y Miquelón",
  "America/Monterrey": "Monterrey, México",
  "America/Montevideo": "Montevideo, Uruguay",
  "America/Nassau": "Nassau, Bahamas",
  "America/New_York": "Nueva York, EE.UU. (Este)",
  "America/Nipigon": "Nipigon, Canadá",
  "America/Nome": "Nome, EE.UU. (Alaska)",
  "America/Noronha": "Islas Fernando de Noronha, Brasil",
  "America/Ojinaga": "Ojinaga, México",
  "America/Panama": "Panamá, Panamá",
  "America/Paraguar": "Asunción, Paraguay",
  "America/Port-au-Prince": "Puerto Príncipe, Haití",
  "America/Porto_Velho": "Porto Velho, Brasil",
  "America/Puerto_Rico": "San Juan, Puerto Rico",
  "America/Rainy_River": "Rainy River, Canadá",
  "America/Rankin_Inlet": "Rankin Inlet, Canadá",
  "America/Recife": "Recife, Brasil",
  "America/Regina": "Regina, Canadá",
  "America/Rio_Branco": "Rio Branco, Brasil",
  "America/Santa_Isabel": "Santa Isabel, México",
  "America/Santarem": "Santarém, Brasil",
  "America/Sao_Paulo": "São Paulo, Brasil",
  "America/Scoresbysund": "Ittoqqortoormiit, Groenlandia",
  "America/Sitka": "Sitka, EE.UU. (Alaska)",
  "America/St_Barthelemy": "Saint-Barthélemy, Saint-Barthélemy",
  "America/St_Johns": "San Juan, Canadá",
  "America/St_Kitts": "Saint Kitts, San Cristóbal y Nieves",
  "America/St_Lucia": "Santa Lucía, Santa Lucía",
  "America/St_Thomas": "Saint Thomas, Islas Vírgenes de EE.UU.",
  "America/St_Vincent":
    "San Vicente y las Granadinas, San Vicente y las Granadinas",
  "America/Tegucigalpa": "Tegucigalpa, Honduras",
  "America/Thule": "Thule, Groenlandia",
  "America/Tijuana": "Tijuana, México",
  "America/Toronto": "Toronto, Canadá",
  "America/Tortola": "Tortola, Islas Vírgenes Británicas",
  "America/Vancouver": "Vancouver, Canadá",
  "America/Whitehorse": "Whitehorse, Canadá",
  "America/Winnipeg": "Winnipeg, Canadá",
  "America/Yakutat": "Yakutat, EE.UU. (Alaska)",
  "America/Yellowknife": "Yellowknife, Canadá",
  "Antarctica/Palmer": "Palmer, Antártida",
  "Antarctica/Rothera": "Rothera, Antártida",
  "Antarctica/Troll": "Troll, Antártida",
  "Arctic/Longyearbyen": "Longyearbyen, Svalbard",
  "Asia/Aden": "Aden, Yemen",
  "Asia/Almaty": "Almaty, Kazajistán",
  "Asia/Amman": "Amán, Jordania",
  "Asia/Anadyr": "Anadyr, Rusia",
  "Asia/Aqtau": "Aqtau, Kazajistán",
  "Asia/Aqtobe": "Aqtobe, Kazajistán",
  "Asia/Ashgabat": "Asjabad, Turkmenistán",
  "Asia/Baghdad": "Bagdad, Irak",
  "Asia/Baku": "Bakú, Azerbaiyán",
  "Asia/Bangkok": "Bangkok, Tailandia",
  "Asia/Barnaul": "Barnaul, Rusia",
  "Asia/Beirut": "Beirut, Líbano",
  "Asia/Bishkek": "Biskek, Kirguistán",
  "Asia/Brunei": "Bandar Seri Begawan, Brunéi",
  "Asia/Chita": "Chita, Rusia",
  "Asia/Choibalsan": "Choibalsan, Mongolia",
  "Asia/Colombo": "Colombo, Sri Lanka",
  "Asia/Damascus": "Damasco, Siria",
  "Asia/Dhaka": "Daca, Bangladés",
  "Asia/Dili": "Dili, Timor Oriental",
  "Asia/Dubai": "Dubái, Emiratos Árabes Unidos",
  "Asia/Dushanbe": "Dusambé, Tayikistán",
  "Asia/Gaza": "Gaza, Palestina",
  "Asia/Hebron": "Hebrón, Palestina",
  "Asia/Ho_Chi_Minh": "Ho Chi Minh, Vietnam",
  "Asia/Hong_Kong": "Hong Kong, Hong Kong",
  "Asia/Hovd": "Hovd, Mongolia",
  "Asia/Irkutsk": "Irkutsk, Rusia",
  "Asia/Jakarta": "Yakarta, Indonesia",
  "Asia/Jayapura": "Jayapura, Indonesia",
  "Asia/Jerusalem": "Jerusalén, Israel",
  "Asia/Kabul": "Kabul, Afganistán",
  "Asia/Kamchatka": "Petropávlovsk-Kamchatski, Rusia",
  "Asia/Karachi": "Karachi, Pakistán",
  "Asia/Kathmandu": "Katmandú, Nepal",
  "Asia/Krasnoyarsk": "Krasnoyarsk, Rusia",
  "Asia/Kuala_Lumpur": "Kuala Lumpur, Malasia",
  "Asia/Kuching": "Kuching, Malasia",
  "Asia/Kuwait": "Kuwait, Kuwait",
  "Asia/Macau": "Macau, Macao",
  "Asia/Magadan": "Magadán, Rusia",
  "Asia/Makassar": "Makassar, Indonesia",
  "Asia/Manila": "Manila, Filipinas",
  "Asia/Muscat": "Mascate, Omán",
  "Asia/Nicosia": "Nicosia, Chipre",
  "Asia/Novokuznetsk": "Novokuznetsk, Rusia",
  "Asia/Novosibirsk": "Novosibirsk, Rusia",
  "Asia/Omsk": "Omsk, Rusia",
  "Asia/Oral": "Oral, Kazajistán",
  "Asia/Phnom_Penh": "Phnom Penh, Camboya",
  "Asia/Pontianak": "Pontianak, Indonesia",
  "Asia/Pyongyang": "Pyongyang, Corea del Norte",
  "Asia/Qatar": "Doha, Catar",
  "Asia/Qostanay": "Kostanay, Kazajistán",
  "Asia/Riyadh": "Riad, Arabia Saudita",
  "Asia/Sakhalin": "Sajalín, Rusia",
  "Asia/Samarkand": "Samarcanda, Uzbekistán",
  "Asia/Seoul": "Seúl, Corea del Sur",
  "Asia/Shanghai": "Shanghái, China",
  "Asia/Singapore": "Singapur, Singapur",
  "Asia/Taipei": "Taipéi, Taiwán",
  "Asia/Tashkent": "Taskent, Uzbekistán",
  "Asia/Tbilisi": "Tiflis, Georgia",
  "Asia/Tehran": "Teherán, Irán",
  "Asia/Tokyo": "Tokio, Japón",
  "Asia/Ulaanbaatar": "Ulán Bator, Mongolia",
  "Asia/Urumqi": "Urumqi, China",
  "Asia/Vientiane": "Vientián, Laos",
  "Asia/Vladivostok": "Vladivostok, Rusia",
  "Asia/Yakutsk": "Yakutsk, Rusia",
  "Asia/Yangon": "Yangon, Birmania",
  "Asia/Yekaterinburg": "Ekaterimburgo, Rusia",
  "Asia/Yerevan": "Ereván, Armenia",
  "Atlantic/Azores": "Azores, Portugal",
  "Atlantic/Bermuda": "Bermudas, Bermudas",
  "Atlantic/Canary": "Islas Canarias, España",
  "Atlantic/Cape_Verde": "Islas de Cabo Verde, Cabo Verde",
  "Atlantic/Faeroe": "Islas Feroe, Dinamarca",
  "Atlantic/Madeira": "Madeira, Portugal",
  "Atlantic/Reykjavik": "Reikiavik, Islandia",
  "Atlantic/South_Georgia": "Georgia del Sur, Georgia del Sur",
  "Atlantic/St_Helena": "Santa Elena, Santa Elena",
  "Australia/Adelaide": "Adelaida, Australia",
  "Australia/Brisbane": "Brisbane, Australia",
  "Australia/Broken_Hill": "Broken Hill, Australia",
  "Australia/Currie": "Currie, Australia",
  "Australia/Darwin": "Darwin, Australia",
  "Australia/Eucla": "Eucla, Australia",
  "Australia/Hobart": "Hobart, Australia",
  "Australia/Lindeman": "Lindeman, Australia",
  "Australia/Lord_Howe": "Lord Howe, Australia",
  "Australia/Melbourne": "Melbourne, Australia",
  "Australia/Perth": "Perth, Australia",
  "Australia/Sydney": "Sídney, Australia",
  "Europe/Amsterdam": "Ámsterdam, Países Bajos",
  "Europe/Andorra": "Andorra la Vieja, Andorra",
  "Europe/Athens": "Atenas, Grecia",
  "Europe/Belgrade": "Belgrado, Serbia",
  "Europe/Berlin": "Berlín, Alemania",
  "Europe/Bratislava": "Bratislava, Eslovaquia",
  "Europe/Brussels": "Bruselas, Bélgica",
  "Europe/Bucharest": "Bucarest, Rumanía",
  "Europe/Budapest": "Budapest, Hungría",
  "Europe/Chisinau": "Chisináu, Moldavia",
  "Europe/Copenhagen": "Copenhague, Dinamarca",
  "Europe/Dublin": "Dublín, Irlanda",
  "Europe/Gibraltar": "Gibraltar, Gibraltar",
  "Europe/Guernsey": "Guernsey, Guernsey",
  "Europe/Helsinki": "Helsinki, Finlandia",
  "Europe/Isle_of_Man": "Isla de Man, Reino Unido",
  "Europe/Istanbul": "Estambul, Turquía",
  "Europe/Jersey": "Jersey, Jersey",
  "Europe/Kaliningrad": "Kaliningrado, Rusia",
  "Europe/Kiev": "Kiev, Ucrania",
  "Europe/Lisbon": "Lisboa, Portugal",
  "Europe/Ljubljana": "Liubliana, Eslovenia",
  "Europe/London": "Londres, Reino Unido",
  "Europe/Luxembourg": "Luxemburgo, Luxemburgo",
  "Europe/Madrid": "Madrid, España",
  "Europe/Malta": "Valeta, Malta",
  "Europe/Mariehamn": "Mariehamn, Åland",
  "Europe/Minsk": "Minsk, Bielorrusia",
  "Europe/Monaco": "Mónaco, Mónaco",
  "Europe/Moscow": "Moscú, Rusia",
  "Europe/Nicosia": "Nicosia, Chipre",
  "Europe/Oslo": "Oslo, Noruega",
  "Europe/Paris": "París, Francia",
  "Europe/Podgorica": "Podgorica, Montenegro",
  "Europe/Prague": "Praga, Chequia",
  "Europe/Riga": "Riga, Letonia",
  "Europe/Rome": "Roma, Italia",
  "Europe/Samara": "Samara, Rusia",
  "Europe/San_Marino": "San Marino, San Marino",
  "Europe/Sarajevo": "Sarajevo, Bosnia y Herzegovina",
  "Europe/Sofia": "Sofía, Bulgaria",
  "Europe/Stockholm": "Estocolmo, Suecia",
  "Europe/Tallinn": "Tallin, Estonia",
  "Europe/Tirane": "Tirana, Albania",
  "Europe/Uzhgorod": "Uzhgorod, Ucrania",
  "Europe/Vaduz": "Vaduz, Liechtenstein",
  "Europe/Vatican": "Ciudad del Vaticano, Ciudad del Vaticano",
  "Europe/Vienna": "Viena, Austria",
  "Europe/Vilnius": "Vilna, Lituania",
  "Europe/Volgograd": "Volgogrado, Rusia",
  "Europe/Warsaw": "Varsovia, Polonia",
  "Europe/Zagreb": "Zagreb, Croacia",
  "Europe/Zaporozhye": "Zaporiyia, Ucrania",
  "Europe/Zurich": "Zúrich, Suiza",
  "Indian/Antananarivo": "Antananarivo, Madagascar",
  "Indian/Chagos": "Chagos, Territorios Británicos del Océano Índico",
  "Indian/Christmas": "Isla de Navidad, Australia",
  "Indian/Cocos": "Islas Cocos, Australia",
  "Indian/Kerguelen": "Islas Kerguelen, Francia",
  "Indian/Mahe": "Mahé, Seychelles",
  "Indian/Maldives": "Malé, Maldivas",
  "Indian/Mauritius": "Mauricio, Mauricio",
  "Indian/Reunion": "Reunión, Francia",
  "Pacific/Apia": "Apia, Samoa",
  "Pacific/Auckland": "Auckland, Nueva Zelanda",
  "Pacific/Chatham": "Chatham Islands, Nueva Zelanda",
  "Pacific/Easter": "Isla de Pascua, Chile",
  "Pacific/Efate": "Efate, Vanuatu",
  "Pacific/Enderbury": "Islas Enderbury, Kiribati",
  "Pacific/Fiji": "Suva, Fiyi",
  "Pacific/Funafuti": "Funafuti, Tuvalu",
  "Pacific/Galapagos": "Galápagos, Ecuador",
  "Pacific/Gambier": "Gambier, Polinesia Francesa",
  "Pacific/Guadalcanal": "Guadalcanal, Islas Salomón",
  "Pacific/Guam": "Guam, Guam",
  "Pacific/Kiritimati": "Kiritimati, Kiribati",
  "Pacific/Kosrae": "Kosrae, Estados Federados de Micronesia",
  "Pacific/Nauru": "Nauru, Nauru",
  "Pacific/Niue": "Niue, Niue",
  "Pacific/Norfolk": "Norfolk, Australia",
  "Pacific/Pago_Pago": "Pago Pago, Samoa Americana",
  "Pacific/Palau": "Palau, Palau",
  "Pacific/Pitcairn": "Pitcairn, Pitcairn",
  "Pacific/Ponape": "Pohnpei, Estados Federados de Micronesia",
  "Pacific/Port_Moresby": "Puerto Moresby, Papúa Nueva Guinea",
  "Pacific/Rarotonga": "Rarotonga, Islas Cook",
  "Pacific/Saipan": "Saipán, Islas Marianas del Norte",
  "Pacific/Tarawa": "Tarawa, Kiribati",
  "Pacific/Tongatapu": "Tongatapu, Tonga",
  "Pacific/Wake": "Wake, Estados Unidos",
  "Pacific/Wallis": "Wallis, Wallis y Futuna",
  "Pacific/West_Bank": "Cisjordania, Palestina",
  "Pacific/Truk": "Truk, Estados Federados de Micronesia",
  "Pacific/Palau": "Palau, Palau",
};

export default cityCountryMapping;
